# Generated by Django 6.0.1 on 2026-01-21 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('Duelist', 'Duelist'), ('Controller', 'Controller'), ('Sentinel', 'Sentinel'), ('Initiator', 'Initiator')], max_length=20)),
                ('pays', models.CharField(blank=True, max_length=50)),
                ('date_sortie', models.DateField()),
                ('biographie', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('categorie', models.CharField(max_length=20)),
                ('prix', models.PositiveIntegerField()),
                ('dommages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('localisation', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capacite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cout', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacites', to='valorant.agent')),
            ],
        ),
    ]
