# Generated by Django 6.0.5 on 2026-05-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Powers',
            new_name='Power',
        ),
    ]
