# Generated by Django 6.0.1 on 2026-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arme',
            old_name='dommages',
            new_name='degats',
        ),
        migrations.AddField(
            model_name='agent',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='arme',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='carte',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m'),
        ),
    ]
