# Generated by Django 6.0.5 on 2026-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0002_rename_powers_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='powers',
        ),
        migrations.AddField(
            model_name='power',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='powers', to='valorant.agent'),
        ),
    ]
