# Generated by Django 6.0.5 on 2026-05-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0003_remove_agent_powers_power_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arme',
            name='author',
        ),
    ]
