# Generated by Django 6.0.5 on 2026-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0004_remove_arme_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
