# Generated by Django 6.0.5 on 2026-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0005_alter_agent_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
